version: 2
jobs:
  install:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - 3.6-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: 3.6-{{ checksum "requirements.txt" }}
  tests:
    working_directory: ~/project
    docker:
    - image: circleci/python:3.6.5
    steps:
    - checkout
    - restore_cache:
        key: 3.6-{{ checksum "requirements.txt" }}
    - run:
        name: run pytest
        command: |
          . venv/bin/activate
          make test

workflows:
  version: 2
  main:
    jobs:
      - install
      - tests:
          requires:
            - install
